name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: 'error'

  readme-lint:
    name: Lint README
    runs-on: ubuntu-latest
    # Skipping README linting per team decision
    if: false
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md
          config_file: .github/workflows/markdownlint.json
          ignore_files: ".markdownlintignore"

  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          find . -name "*.json" -type f | xargs -I {} sh -c "echo 'Validating {}...' && cat {} | jq . > /dev/null || exit 1"